### PR TITLE
Use the lodash.assign package instead of importing all of lodash

### PR DESCRIPTION
**Pull request by wesleytodd**
Updates to the new lodash package where you don't need to install all of lodash anymore.

### CODE REVIEW

**Comment by gcanti** [comment]
Hi,

Back in the day I based my decision on these facts:
- if you already have lodash as dependency, this library will utilise that
- if you have not lodash as dependency (unlikely?), this library adds lodash as a new dependency but just imports `'lodash/object/assign'`

Do you think it's a problem to install the whole lodash in the latter case?

**Comment by wesleytodd** [comment]
Unless the user is also using a matching version of lodash this doesn't really give any benefit.  And for this lib in particular it is a whole major version behind right now.  So I think that going with the smallest possible footprint is best.  Also, FWIW, even lodash's implementation of this is not as small as something like this minimalistic module: https://www.npmjs.com/package/object-assign

**Comment by gcanti** [comment]
I see. Thanks for the heads up. Speaking of going minimalistic, what if we discard lodash for a simple `mixin` function?

``` js
function mixin(x, y) {
  for (var k in y) {
    if (y.hasOwnProperty(k)) {
      x[k] = y[k];
    }
  }
  return x;
}

...

function formatNumber(n, options) {
  options = mixin(mixin({}, defaults), options);
  ...
}

...
```

**Comment by wesleytodd** [comment]
The benifit of using something like that `object-assign` module is that it defaults to using the built in `Object.assign` implementation, which should be more performant and future compatible.  Writing your own is fine, but if you look at that module you will see it has to do a fair bit of stuff to get cross platform compliance, which personally I prefer to just use the popular module, but that is just personal preference.

Check here for how that module handles the fallbacks: https://github.com/sindresorhus/object-assign/blob/master/index.js#L14

**Comment by wesleytodd** [comment]
https://github.com/sindresorhus/object-assign/blob/master/index.js#L29

This is what I mean about compliance, this one supports symbols from es2015, so the assumption is that that module will continue to update without you having to keep up.

**Comment by wesleytodd** [comment]
I just went in and re-read the code, so I have one more comment :)

When I am doing this and only have a small number of options I just hard code them to avoid having un-necessary deps or helper methods.  So again, personal opinion here, but I would just do this:

``` javascript
options = options || {};
options.fractionDigits = options.fractionDigits || 2;
options.useGrouping = options.useGrouping || true;
options.symbols = options.symbols || {
  grouping: ',',
  decimal: '.'
};
```

This greatly reduces the overall code size and is also more performant at runtime.

**Comment by gcanti** [comment]
So you are proposing to use `object-assign` instead of `lodash.assign`, right?

EDIT: posted before your last comment

**Comment by gcanti** [comment]
I haven't a strong opinion on the subject. I'm fine with a `mixin` function, with `object-assign` and even better with your last proposal. However I think it should use some `typeof ... ===  "undefined"` checks:

``` js
options.fractionDigits = options.fractionDigits || 2; // options.fractionDigits can be = 0
options.useGrouping = options.useGrouping || true; // options.useGrouping can be false
```

**Comment by wesleytodd** [comment]
Yeah, good catch, just wrote that out really quick without any running code :)

Ill update the PR!

**Comment by gcanti** [comment]
:+1:

**Comment by wesleytodd** [comment]
Yep, just copy paste.  Good catch!  I just did it and ran the tests, and because 2 is truthy it still worked lol.  Updated!

**Comment by gcanti** [comment]
@wesleytodd build failed: the default value for `options.useGrouping` is `true`

**Comment by wesleytodd** [comment]
lol, wow, I was clearly not paying attention well last night.  Fixed, actually ran the tests, and pushed.

**Comment by gcanti** [comment]
Nice, thanks.

**Comment by gcanti** [comment]
Released https://github.com/gcanti/simple-format-number/releases/tag/v0.1.2

**Pull request merged**
